CREATE DATABASE [IF NOT EXISTS]
alcidion;
USE alcidion;

CREATE TABLE patient (
  id INT NOT NULL UNIQUE AUTO_INCREMENT,
  lastName VARCHAR
(50) NOT NULL,
  firstName VARCHAR
(50) NOT NULL,
  age INT
(3) NOT NULL,
  sex INT
(1) NOT NULL,
  PRIMARY KEY
(id)
);

CREATE TABLE [IF NOT EXISTS] areas
(
  id INT NOT NULL UNIQUE AUTO_INCREMENT,
  areaName VARCHAR
(70) NOT NULL,
)

CREATE TABLE [IF NOT EXISTS] doctor
(
  id INT NOT NULL UNIQUE AUTO_INCREMENT,
    lastName VARCHAR
(50) NOT NULL,
     firstName VARCHAR
(50) NOT NULL,
)

CREATE TABLE [IF NOT EXISTS] record
(
  id INT NOT NULL UNIQUE AUTO_INCREMENT,
  patient_id INT NOT NULL,
  doctor_id INT NOT NULL,
  description VARCHAR
(500) NOT NULL,
)

CREATE TABLE [IF NOT EXISTS] nurse
(
  id INT NOT NULL UNIQUE AUTO_INCREMENT,
  lastName VARCHAR
(255) NOT NULL,
  firstName VARCHAR
(255) NOT NULL,

)